# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'puma', '~> 6.4'
gem 'rack', '~> 3.0'
gem 'sinatra', '~> 4.0'

gem 'rackup', '~> 2.1'

gem 'sinatra-cors', '~> 1.2'

group :development do
  gem 'rubocop'
end
